# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, default='my location', max_length=120, null=True)),
                ('job', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
